# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sjguo/work/baidu/proteus

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sjguo/work/baidu/proteus

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sjguo/work/baidu/proteus/CMakeFiles /home/sjguo/work/baidu/proteus/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sjguo/work/baidu/proteus/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named intrinsics_gen

# Build rule for target.
intrinsics_gen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 intrinsics_gen
.PHONY : intrinsics_gen

# fast build rule for target.
intrinsics_gen/fast:
	$(MAKE) -f CMakeFiles/intrinsics_gen.dir/build.make CMakeFiles/intrinsics_gen.dir/build
.PHONY : intrinsics_gen/fast

#=============================================================================
# Target rules for targets named Proteus

# Build rule for target.
Proteus: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Proteus
.PHONY : Proteus

# fast build rule for target.
Proteus/fast:
	$(MAKE) -f CMakeFiles/Proteus.dir/build.make CMakeFiles/Proteus.dir/build
.PHONY : Proteus/fast

Executor.o: Executor.cpp.o

.PHONY : Executor.o

# target to build an object file
Executor.cpp.o:
	$(MAKE) -f CMakeFiles/Proteus.dir/build.make CMakeFiles/Proteus.dir/Executor.cpp.o
.PHONY : Executor.cpp.o

Executor.i: Executor.cpp.i

.PHONY : Executor.i

# target to preprocess a source file
Executor.cpp.i:
	$(MAKE) -f CMakeFiles/Proteus.dir/build.make CMakeFiles/Proteus.dir/Executor.cpp.i
.PHONY : Executor.cpp.i

Executor.s: Executor.cpp.s

.PHONY : Executor.s

# target to generate assembly for a file
Executor.cpp.s:
	$(MAKE) -f CMakeFiles/Proteus.dir/build.make CMakeFiles/Proteus.dir/Executor.cpp.s
.PHONY : Executor.cpp.s

FuncSummaryPass.o: FuncSummaryPass.cpp.o

.PHONY : FuncSummaryPass.o

# target to build an object file
FuncSummaryPass.cpp.o:
	$(MAKE) -f CMakeFiles/Proteus.dir/build.make CMakeFiles/Proteus.dir/FuncSummaryPass.cpp.o
.PHONY : FuncSummaryPass.cpp.o

FuncSummaryPass.i: FuncSummaryPass.cpp.i

.PHONY : FuncSummaryPass.i

# target to preprocess a source file
FuncSummaryPass.cpp.i:
	$(MAKE) -f CMakeFiles/Proteus.dir/build.make CMakeFiles/Proteus.dir/FuncSummaryPass.cpp.i
.PHONY : FuncSummaryPass.cpp.i

FuncSummaryPass.s: FuncSummaryPass.cpp.s

.PHONY : FuncSummaryPass.s

# target to generate assembly for a file
FuncSummaryPass.cpp.s:
	$(MAKE) -f CMakeFiles/Proteus.dir/build.make CMakeFiles/Proteus.dir/FuncSummaryPass.cpp.s
.PHONY : FuncSummaryPass.cpp.s

PDA.o: PDA.cpp.o

.PHONY : PDA.o

# target to build an object file
PDA.cpp.o:
	$(MAKE) -f CMakeFiles/Proteus.dir/build.make CMakeFiles/Proteus.dir/PDA.cpp.o
.PHONY : PDA.cpp.o

PDA.i: PDA.cpp.i

.PHONY : PDA.i

# target to preprocess a source file
PDA.cpp.i:
	$(MAKE) -f CMakeFiles/Proteus.dir/build.make CMakeFiles/Proteus.dir/PDA.cpp.i
.PHONY : PDA.cpp.i

PDA.s: PDA.cpp.s

.PHONY : PDA.s

# target to generate assembly for a file
PDA.cpp.s:
	$(MAKE) -f CMakeFiles/Proteus.dir/build.make CMakeFiles/Proteus.dir/PDA.cpp.s
.PHONY : PDA.cpp.s

PDA2Dot.o: PDA2Dot.cpp.o

.PHONY : PDA2Dot.o

# target to build an object file
PDA2Dot.cpp.o:
	$(MAKE) -f CMakeFiles/Proteus.dir/build.make CMakeFiles/Proteus.dir/PDA2Dot.cpp.o
.PHONY : PDA2Dot.cpp.o

PDA2Dot.i: PDA2Dot.cpp.i

.PHONY : PDA2Dot.i

# target to preprocess a source file
PDA2Dot.cpp.i:
	$(MAKE) -f CMakeFiles/Proteus.dir/build.make CMakeFiles/Proteus.dir/PDA2Dot.cpp.i
.PHONY : PDA2Dot.cpp.i

PDA2Dot.s: PDA2Dot.cpp.s

.PHONY : PDA2Dot.s

# target to generate assembly for a file
PDA2Dot.cpp.s:
	$(MAKE) -f CMakeFiles/Proteus.dir/build.make CMakeFiles/Proteus.dir/PDA2Dot.cpp.s
.PHONY : PDA2Dot.cpp.s

Utils.o: Utils.cpp.o

.PHONY : Utils.o

# target to build an object file
Utils.cpp.o:
	$(MAKE) -f CMakeFiles/Proteus.dir/build.make CMakeFiles/Proteus.dir/Utils.cpp.o
.PHONY : Utils.cpp.o

Utils.i: Utils.cpp.i

.PHONY : Utils.i

# target to preprocess a source file
Utils.cpp.i:
	$(MAKE) -f CMakeFiles/Proteus.dir/build.make CMakeFiles/Proteus.dir/Utils.cpp.i
.PHONY : Utils.cpp.i

Utils.s: Utils.cpp.s

.PHONY : Utils.s

# target to generate assembly for a file
Utils.cpp.s:
	$(MAKE) -f CMakeFiles/Proteus.dir/build.make CMakeFiles/Proteus.dir/Utils.cpp.s
.PHONY : Utils.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/Proteus.dir/build.make CMakeFiles/Proteus.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/Proteus.dir/build.make CMakeFiles/Proteus.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/Proteus.dir/build.make CMakeFiles/Proteus.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... intrinsics_gen"
	@echo "... Proteus"
	@echo "... Executor.o"
	@echo "... Executor.i"
	@echo "... Executor.s"
	@echo "... FuncSummaryPass.o"
	@echo "... FuncSummaryPass.i"
	@echo "... FuncSummaryPass.s"
	@echo "... PDA.o"
	@echo "... PDA.i"
	@echo "... PDA.s"
	@echo "... PDA2Dot.o"
	@echo "... PDA2Dot.i"
	@echo "... PDA2Dot.s"
	@echo "... Utils.o"
	@echo "... Utils.i"
	@echo "... Utils.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

